USE diente_leon;
CREATE ROLE 'admin1', 'lector1', 'escritor1';
GRANT ALL ON diente_leon.* TO 'admin1';
GRANT SELECT ON diente_leon.* TO 'lector1';
GRANT INSERT, UPDATE, DELETE ON diente_leon.* TO 'escritor1';
CREATE USER 'admin'@'localhost' IDENTIFIED BY '123';
CREATE USER 'lector3'@'localhost' IDENTIFIED BY '123';
CREATE USER 'lector2'@'localhost' IDENTIFIED BY '123';
CREATE USER 'escritor'@'localhost' IDENTIFIED BY '123';
GRANT 'admin1' TO 'admin'@'localhost';
GRANT 'lector1' TO 'lector3'@'localhost', 'lector2'@'localhost';
GRANT 'escritor1' TO 'escritor'@'localhost';